begin
T7BlockSelectStatus.Value := False;
T7OpenStatus1.Value := False; // Останавливаем выполнение скрипта
T7OpenStatus2.Value := False; // Останавливаем выполнение скрипта
T7OpenStatus3.Value := False; // Останавливаем выполнение скрипта
T7OpenStatus4.Value := False; // Останавливаем выполнение скрипта
T7OpenStatus5.Value := False; // Останавливаем выполнение скрипта
T7OpenStatus6.Value := False; // Останавливаем выполнение скрипта
T7OpenStatus7.Value := False; // Останавливаем выполнение скрипта
T7OpenStatus8.Value := False; // Останавливаем выполнение скрипта
T7OpenStatus9.Value := False; // Останавливаем выполнение скрипта
T7OpenStatus10.Value := False; // Останавливаем выполнение скрипта
T7LatchRunOpen.Value := False;   // Дискретный выход управления задвижкой
T7CloseStatus1.Value := False; // Останавливаем выполнение скрипта
T7CloseStatus2.Value := False; // Останавливаем выполнение скрипта
T7CloseStatus3.Value := False; // Останавливаем выполнение скрипта
T7CloseStatus4.Value := False; // Останавливаем выполнение скрипта
T7CloseStatus5.Value := False; // Останавливаем выполнение скрипта
T7CloseStatus6.Value := False; // Останавливаем выполнение скрипта
T7CloseStatus7.Value := False; // Останавливаем выполнение скрипта
T7CloseStatus8.Value := False; // Останавливаем выполнение скрипта
T7CloseStatus9.Value := False; // Останавливаем выполнение скрипта
T7CloseStatus10.Value := False; // Останавливаем выполнение скрипта
T7LatchRunClose.Value := False;   // Дискретный выход управления задвижкой
T7OpenTimer1.Value := 0;
T7OpenTimer2.Value := 0;
T7OpenTimer3.Value := 0;
T7OpenTimer4.Value := 0;
T7OpenTimer5.Value := 0;
T7OpenTimer6.Value := 0;
T7OpenTimer7.Value := 0;
T7OpenTimer8.Value := 0;
T7OpenTimer9.Value := 0;
T7OpenTimer10.Value := 0;
T7CloseTimer1.Value := 0;
T7CloseTimer2.Value := 0;
T7CloseTimer3.Value := 0;
T7CloseTimer4.Value := 0;
T7CloseTimer5.Value := 0;
T7CloseTimer6.Value := 0;
T7CloseTimer7.Value := 0;
T7CloseTimer8.Value := 0;                               
T7CloseTimer9.Value := 0;
T7CloseTimer10.Value := 0;
T7CalStatus1.Value := False; // Останавливаем выполнение скрипта
T7CalStatus2.Value := False; // Останавливаем выполнение скрипта
T7CalStatus3.Value := False; // Останавливаем выполнение скрипта
T7CalStatus4.Value := False; // Останавливаем выполнение скрипта
T7CalStatus5.Value := False; // Останавливаем выполнение скрипта
T7CalStatus6.Value := False; // Останавливаем выполнение скрипта
T7CalStatus7.Value := False; // Останавливаем выполнение скрипта
T7CalStatus8.Value := False; // Останавливаем выполнение скрипта
T7CalStatus9.Value := False; // Останавливаем выполнение скрипта
T7CalStatus10.Value := False; // Останавливаем выполнение скрипта
T7CalTimer1.Value := 0;
T7CalTimer2.Value := 0;                
T7CalTimer3.Value := 0;
T7CalTimer4.Value := 0;
T7CalTimer5.Value := 0;
T7CalTimer6.Value := 0;
T7CalTimer7.Value := 0;
T7CalTimer8.Value := 0;
T7CalTimer9.Value := 0;
T7CalTimer10.Value := 0;
T7LatchSelect1.Value := False;
T7LatchSelect2.Value := False;
T7LatchSelect3.Value := False;
T7LatchSelect4.Value := False;
T7LatchSelect5.Value := False;
T7LatchSelect6.Value := False;
T7LatchSelect7.Value := False;
T7LatchSelect8.Value := False;
T7LatchSelect9.Value := False;
T7LatchSelect10.Value := False;
end.
